#!/usr/bin/env bash
# Phase 01: assemble the splat output and link it into a symbol-rich ELF.
#
# This is an ASSEMBLY-ONLY link: symbol names, addresses and sizes, with no
# recovered C. The result is what N64Recomp consumes in phase 02. Everything it
# produces is derived from the builder's own dump and is never committed.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

AS=mips-linux-gnu-as
LD=mips-linux-gnu-ld
OBJCOPY=mips-linux-gnu-objcopy
# macro.inc lives in recomp/, not asm/: asm/ is generated and gets deleted
# wholesale on a re-split.
ASFLAGS="-march=vr4300 -mabi=32 -EB -no-pad-sections -I recomp"

mkdir -p build/asm build/assets elf

echo "=== assembling ==="
# Recursive: splat puts data subsegments in a directory under asm/, and the
# generated linker script references them by that nested path.
while IFS= read -r f; do
    o="build/$f.o"
    mkdir -p "$(dirname "$o")"
    $AS $ASFLAGS "$f" -o "$o"
    printf '  %-34s -> %s\n' "$f" "$o"
done < <(find asm -name '*.s' | sort)

echo "=== wrapping binary segments ==="
for f in assets/ipl3.bin assets/assets.bin; do
    [ -f "$f" ] || continue
    o="build/$f.o"
    $OBJCOPY -I binary -O elf32-tradbigmips -B mips \
             --rename-section .data=.data,alloc,load,readonly,data,contents \
             "$f" "$o"
    printf '  %-34s -> %s\n' "$f" "$o"
done

# splat's auto-symbol fragments must be filtered before use: an assignment for
# a symbol that an object already defines would shadow the real, section-bound
# definition with an ABSOLUTE one. See tools/gen_link_syms.py.
echo "=== resolving symbol assignments ==="
python3 tools/gen_link_syms.py $(find build/asm -name '*.o' | sort)

echo "=== combining linker scripts ==="
LINK_LD=build/rayman2.us.link.ld
{
    echo "/* generated by scripts/build-elf.sh -- do not edit */"
    cat build/link_syms.ld
    cat recomp/rayman2.us.ld
} > "$LINK_LD"
printf '  %s (%s lines)\n' "$LINK_LD" "$(wc -l < "$LINK_LD")"

echo "=== linking ==="
$LD -T "$LINK_LD" -Map build/rayman2.us.map --no-check-sections \
    -o elf/rayman2.us.elf

echo "=== result ==="
ls -l elf/rayman2.us.elf
mips-linux-gnu-readelf -SW elf/rayman2.us.elf | grep -E 'PROGBITS|NOBITS'
