#!/usr/bin/env bash
# Phase 01: assemble the splat output and link it into a symbol-rich ELF.
#
# This is an ASSEMBLY-ONLY link: symbol names, addresses and sizes, with no
# recovered C. The result is what N64Recomp consumes in phase 02. Everything it
# produces is derived from the builder's own dump and is never committed.
set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO"

AS=mips-linux-gnu-as
LD=mips-linux-gnu-ld
OBJCOPY=mips-linux-gnu-objcopy
ASFLAGS="-march=vr4300 -mabi=32 -EB -no-pad-sections -I asm"

mkdir -p build/asm build/assets elf

echo "=== assembling ==="
for f in asm/*.s; do
    o="build/$f.o"
    $AS $ASFLAGS "$f" -o "$o"
    printf '  %-16s -> %s\n' "$f" "$o"
done

echo "=== wrapping binary segments ==="
for f in assets/ipl3.bin assets/assets.bin; do
    [ -f "$f" ] || continue
    o="build/$f.o"
    $OBJCOPY -I binary -O elf32-tradbigmips -B mips \
             --rename-section .data=.data,alloc,load,readonly,data,contents \
             "$f" "$o"
    printf '  %-20s -> %s\n' "$f" "$o"
done

echo "=== resolving unlabelled references ==="
python3 tools/gen_missing_syms.py build/asm/*.o

# splat emits its auto-symbol files as linker-script fragments of plain
# assignments: references that land outside the three loaded segments -- bss,
# and hardware registers such as 0xB8000000. gen_missing_syms.py adds the ones
# that land *inside* a segment but inside another object, which splat does not
# label. All are concatenated ahead of the generated SECTIONS block into a
# single script, so there is no ambiguity about how ld combines multiple -T
# arguments.
echo "=== combining linker scripts ==="
LINK_LD=build/rayman2.us.link.ld
{
    echo "/* generated by scripts/build-elf.sh -- do not edit */"
    cat recomp/undefined_syms_auto.txt
    cat recomp/undefined_funcs_auto.txt
    cat recomp/undefined_syms_extra.txt
    cat recomp/rayman2.us.ld
} > "$LINK_LD"
printf '  %s (%s lines)\n' "$LINK_LD" "$(wc -l < "$LINK_LD")"

echo "=== linking ==="
$LD -T "$LINK_LD" -Map build/rayman2.us.map --no-check-sections \
    -o elf/rayman2.us.elf

echo "=== result ==="
ls -l elf/rayman2.us.elf
mips-linux-gnu-readelf -SW elf/rayman2.us.elf | grep -E '\.boot|\.main|\.aux' || true
