#!/usr/bin/env python3
"""Declare function symbols at call targets splat did not classify as functions.

splat finds function boundaries from control flow, which recovers most of them
but not all: a routine only ever reached through a jump table or a function
pointer has no incoming `jal`, and a routine whose caller splat placed in a data
region is not followed either. N64Recomp then refuses the calling function with
"No function found for jal target", because it cannot emit a call to something
that has no symbol.

Every `jal` in the ROM names its target absolutely, so the missing symbols can
be recovered directly: scan the code for call targets, subtract the function
symbols the ELF already has, and declare the remainder. splat reads the result
on the next split and emits real labels for them.

This is the JAL-target pass the build plan calls for, and it converges: each
round can reveal code that was previously undecoded, so run it until it reports
nothing new (scripts/refine-syms.sh does that).

Usage:  python tools/gen_missing_funcs.py rom.z64 elf/rayman2.us.elf
        (writes recomp/auto_funcs.txt)
"""
import pathlib
import re
import struct
import subprocess
import sys

READELF = "mips-linux-gnu-readelf"
OUT = pathlib.Path("recomp/auto_funcs.txt")

# The three loaded segments, and the extent of the CODE within each -- the
# trailing data of every segment is excluded, so a word in a data table that
# happens to decode as a `jal` cannot invent a function. Values come from the
# segment map in docs/PHASE01-FINDINGS.md and match recomp/rayman2.us.yaml.
#           name    rom_start  code_end(rom)  vram_start
SEGMENTS = [("boot", 0x001000, 0x01A860, 0x80000400),
            ("main", 0x01DCC0, 0x0BEE10, 0x80025C50),
            ("aux",  0x0C5BF0, 0x0D0100, 0x800F64A0)]


# splat's generated name for data it could not attribute to a function.
DATA_NAME = re.compile(r"^(?:D|jtbl|jpt)_[0-9A-Fa-f]{8}$")


def existing_funcs(elf: str) -> set[int]:
    """Addresses that already carry a symbol naming them as CODE.

    Deliberately keyed on the name, not the ELF type: macro.inc types every
    `glabel` as @function, data labels included, so the type says nothing. An
    address splat called `D_<addr>` is being treated as data -- it will land in
    the ignored list -- so if a `jal` targets it, it is missing a function
    symbol and must be declared as one here.
    """
    out = subprocess.run([READELF, "-sW", elf], capture_output=True, text=True, check=True).stdout
    addrs = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 8 and parts[0].endswith(":") and parts[3] == "FUNC":
            if not DATA_NAME.match(parts[7]):
                addrs.add(int(parts[1], 16))
    return addrs


def call_targets(rom: bytes) -> dict[int, int]:
    """Absolute `jal` targets that land inside one of the code ranges."""
    ranges = [(v, v + (ce - rs)) for _n, rs, ce, v in SEGMENTS]
    hits: dict[int, int] = {}
    for _name, rom_start, code_end, vram in SEGMENTS:
        seg = rom[rom_start:code_end]
        words = struct.unpack(f">{len(seg) // 4}I", seg)
        for i, w in enumerate(words):
            if (w >> 26) != 3:                       # jal
                continue
            pc = vram + i * 4
            t = (pc & 0xF0000000) | ((w & 0x03FFFFFF) << 2)
            if any(lo <= t < hi for lo, hi in ranges):
                hits[t] = hits.get(t, 0) + 1
    return hits


def main() -> int:
    if len(sys.argv) != 3:
        raise SystemExit(f"usage: {sys.argv[0]} <rom> <elf>")
    rom = open(sys.argv[1], "rb").read()

    have = existing_funcs(sys.argv[2])
    targets = call_targets(rom)
    missing = sorted(t for t in targets if t not in have)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="\n") as f:
        f.write("// Generated by tools/gen_missing_funcs.py -- do not edit.\n")
        f.write("// Call targets that splat did not classify as functions.\n")
        for addr in missing:
            f.write(f"func_{addr:08X} = 0x{addr:08X}; // type:func\n")

    print(f"call targets in code : {len(targets)}")
    print(f"already symbols      : {len(targets) - len(missing)}")
    print(f"newly declared       : {len(missing)}  -> {OUT}")
    for a in missing[:8]:
        print(f"    0x{a:08X}  ({targets[a]} call sites)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
