#!/usr/bin/env python3
"""Build the linker-script symbol fragment, without shadowing real definitions.

Two sources of plain `NAME = 0xADDR;` assignments feed the link:

  * splat's `undefined_syms_auto.txt` / `undefined_funcs_auto.txt`, for
    references it could not resolve, and
  * addresses referenced from inside another object, which splat references by
    a name encoding the address but never labels.

Both are necessary, and both are dangerous in the same way: an assignment
defines the symbol as ABSOLUTE. If the symbol is also defined properly in one
of the assembled objects -- which is the normal case for any call from one
segment into another -- the absolute definition shadows the real, section-bound
one. The link still succeeds and the bytes still come out identical, because
the address is the same either way, so nothing looks wrong. But the symbol is
no longer attached to a section, and any consumer that resolves symbols by
section stops seeing it. N64Recomp is such a consumer: it reports
"No function found for jal target" for a function that is plainly right there.

So: emit an assignment only for a symbol that no object defines.

Usage:  python tools/gen_link_syms.py <objects...>
        (writes build/link_syms.ld)
"""
import pathlib
import re
import subprocess
import sys

NM = "mips-linux-gnu-nm"
OUT = pathlib.Path("build/link_syms.ld")
FRAGMENTS = [pathlib.Path("recomp/undefined_syms_auto.txt"),
             pathlib.Path("recomp/undefined_funcs_auto.txt")]

ASSIGN = re.compile(r"^\s*([A-Za-z_][A-Za-z0-9_]*)\s*=\s*(0x[0-9A-Fa-f]+|\d+)\s*;")
ADDR_NAME = re.compile(r"^(?:D|func|jtbl|jpt|L)_([0-9A-Fa-f]{8})$")


def symbols(objs: list[str]) -> tuple[set[str], set[str]]:
    out = subprocess.run([NM, *objs], capture_output=True, text=True, check=True).stdout
    undef, defined = set(), set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) == 2 and parts[0] == "U":
            undef.add(parts[1])
        elif len(parts) == 3 and parts[1] != "U":
            defined.add(parts[2])
    return undef, defined


def main() -> int:
    objs = sys.argv[1:]
    if not objs:
        raise SystemExit(f"usage: {sys.argv[0]} <object files>")

    undef, defined = symbols(objs)

    emitted: dict[str, str] = {}
    shadowed = 0
    for frag in FRAGMENTS:
        if not frag.exists():
            continue
        for line in frag.read_text().splitlines():
            m = ASSIGN.match(line)
            if not m:
                continue
            name, value = m.group(1), m.group(2)
            if name in defined:
                shadowed += 1          # a real definition exists; do not shadow it
                continue
            emitted.setdefault(name, value)

    # References no object defines and no fragment covers. Their names encode
    # their addresses, so they can be defined mechanically.
    unresolved = []
    for name in sorted(undef - defined - set(emitted)):
        m = ADDR_NAME.match(name)
        if m:
            emitted[name] = f"0x{m.group(1).upper()}"
        else:
            unresolved.append(name)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="\n") as f:
        f.write("/* Generated by tools/gen_link_syms.py -- do not edit. */\n")
        for name, value in sorted(emitted.items()):
            f.write(f"{name} = {value};\n")

    print(f"assignments emitted : {len(emitted)}  -> {OUT}")
    print(f"suppressed (defined): {shadowed}   <- would have shadowed a real symbol")
    if unresolved:
        print(f"UNRESOLVED          : {len(unresolved)}  (no address in the name)")
        for n in unresolved[:20]:
            print(f"    {n}")
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
