#!/usr/bin/env python3
"""Emit linker assignments for symbols splat referenced but never defined.

splat labels the addresses it can attribute to a symbol. A reference that lands
*inside* another object -- the middle of an array, a jump-table entry, a struct
field reached by its own %hi/%lo pair -- is emitted as a reference to a name of
the form `D_800C8C24`, but no label is produced at that address, so the link
fails with an undefined reference.

Those names encode their own address, so the definition is mechanical: read the
undefined symbols out of the assembled objects and write `NAME = 0xADDRESS;`
for every one whose name carries an address. Symbols that do not encode an
address are reported and left alone -- those are real problems, not bookkeeping.

Usage:  python tools/gen_missing_syms.py build/asm/*.o
        (writes recomp/undefined_syms_extra.txt)
"""
import pathlib
import re
import subprocess
import sys

NM = "mips-linux-gnu-nm"
OUT = pathlib.Path("recomp/undefined_syms_extra.txt")
ALREADY = [pathlib.Path("recomp/undefined_syms_auto.txt"),
           pathlib.Path("recomp/undefined_funcs_auto.txt")]

# Names splat generates that carry their own address.
ADDR_NAME = re.compile(r"^(?:D|func|jtbl|jpt|L)_([0-9A-Fa-f]{8})$")


def defined_already() -> set[str]:
    seen: set[str] = set()
    for p in ALREADY:
        if not p.exists():
            continue
        for line in p.read_text().splitlines():
            name = line.split("=", 1)[0].strip()
            if name:
                seen.add(name)
    return seen


def undefined_symbols(objs: list[str]) -> set[str]:
    out = subprocess.run([NM, "-u", *objs], capture_output=True, text=True, check=True).stdout
    syms: set[str] = set()
    for line in out.splitlines():
        parts = line.split()
        if len(parts) >= 2 and parts[-2] == "U":
            syms.add(parts[-1])
        elif len(parts) == 2 and parts[0] == "U":
            syms.add(parts[1])
    return syms


def main() -> int:
    objs = sys.argv[1:]
    if not objs:
        raise SystemExit(f"usage: {sys.argv[0]} <object files>")

    known = defined_already()
    undef = undefined_symbols(objs) - known

    resolved, unresolved = {}, []
    for s in sorted(undef):
        m = ADDR_NAME.match(s)
        if m:
            resolved[s] = int(m.group(1), 16)
        else:
            unresolved.append(s)

    OUT.parent.mkdir(parents=True, exist_ok=True)
    with OUT.open("w", newline="\n") as f:
        f.write("/* Generated by tools/gen_missing_syms.py -- do not edit.\n"
                " * Addresses splat referenced from inside another object and so\n"
                " * never labelled. Each name encodes its own address. */\n")
        for name, addr in sorted(resolved.items(), key=lambda kv: kv[1]):
            f.write(f"{name} = 0x{addr:08X};\n")

    print(f"undefined symbols   : {len(undef)}")
    print(f"address-encoded     : {len(resolved)}  -> {OUT}")
    if unresolved:
        print(f"NOT address-encoded : {len(unresolved)}  (these need real attention)")
        for s in unresolved[:20]:
            print(f"    {s}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
