// rayman-2-the-great-escape-recomp — runtime host.
//
// Brings up the pieces the recompiled game needs and hands control to
// librecomp: an SDL window for RT64 to attach to, audio and input callbacks,
// and the game entry that ties the player's ROM to the recompiled entrypoint.
//
// Written against THIS repository's pinned runtime (lib/N64ModernRuntime, the
// controller-pak branch). Every callback signature below was read out of the
// vendored headers rather than assumed, because they differ between forks.

#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <exception>
#include <cstdlib>
#include <cstring>
#include <stdexcept>
#include <filesystem>
#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/error_handling.hpp"
#include "ultramodern/input.hpp"
#include "ultramodern/threads.hpp"

#include "controller_pak.h"
#include "capture.h"
#include "debug_report.h"

#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"

#define SDL_MAIN_HANDLED
#include <SDL.h>
#ifdef _WIN32
#include <ShlObj.h>      // SHGetKnownFolderPath, for the per-user config path.
#include <objbase.h>     // CoTaskMemFree, which SHGetKnownFolderPath allocates with.
#include <SDL_syswm.h>   // SDL_GetWindowWMInfo -> native HWND.
                         // Windows only: on Linux the WindowHandle IS the
                         // SDL_Window*, and this header drags in <X11/X.h>,
                         // whose `None` macro collides with enumerators such as
                         // Device::None and Pak::None.
#include <timeapi.h>     // timeBeginPeriod; links winmm
#endif

#ifdef RAYMAN2_ENABLE_FRONTEND
#include "recompui/recompui.h"
#include "recompui/program_config.h"   // recompui::programconfig::set_program_*
#include "recompui/config.h"           // recompui::config::sound::get_main_volume
#endif

// ---------------------------------------------------------------------------
// Generated by N64Recomp into RecompiledFuncs/. Declared, never defined here.
// ---------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// librecomp's address -> function lookup. Declared here only so that
// RAYMAN2_SELFTEST=nullcall can exercise its failure path; nothing else in
// the port calls it, because every call to it is generated.
extern "C" recomp_func_t* get_function(int32_t addr);

// The game's entry point, wrapped so that crossing into recompiled code is
// visible in the log. This is the phase 03 gate: everything before it is host
// setup, everything after it is Rayman 2's own code running.
// The base of emulated RDRAM, remembered the moment the game gets it.
//
// Nothing else hands it to the port's own threads: the gfx callbacks take no
// rdram argument, so a capture taken from the event pump would otherwise have
// no way to read the framebuffer the game is presenting. This is the only place
// the pointer arrives, and it does not move afterwards.
std::atomic<uint8_t*> g_rdram{nullptr};

extern "C" void rayman2_entrypoint(uint8_t* rdram, recomp_context* ctx) {
    g_rdram.store(rdram, std::memory_order_release);
    std::fprintf(stderr, "[rayman2] entering recomp_entrypoint -- the game thread is running\n");
    recomp_entrypoint(rdram, ctx);
    std::fprintf(stderr, "[rayman2] recomp_entrypoint returned\n");
}
gpr get_entrypoint_address();

// src/rsp.cpp
RspUcodeFunc* rayman2_get_rsp_microcode(const OSTask* task);

// src/register_sections.cpp — hands N64Recomp's section tables to librecomp so
// game-side addresses can be resolved back to recompiled functions.
void rayman2_register_sections();

// src/crash_report.cpp -- prints a located fault instead of exiting silently.
void rayman2_install_crash_reporter();

// src/thread_sampler.cpp -- opt-in (RAYMAN2_SAMPLE) profile of where the
// game's threads actually are, for when nothing crashes and nothing draws.
void rayman2_start_thread_sampler();
void rayman2_stop_thread_sampler();

// src/rt64_context.cpp -- set true once the renderer has presented a frame.
namespace rayman2 { std::atomic<bool>& vi_has_ticked(); }
// src/draw_distance.cpp
namespace rayman2 { void update_widescreen_policy(int window_width, int window_height); }
// src/frame_pacing.cpp -- gives the game back the frame rate the RDP imposed.
namespace rayman2 { void install_frame_pacing(); }
// src/demo_scan.cpp -- RAYMAN2_DEMOSCAN only; a no-op otherwise.
namespace rayman2 { void demo_scan_poll(const uint8_t* rdram); }

#ifdef RAYMAN2_ENABLE_FRONTEND
// src/frontend.cpp -- the launcher, config menus and input binding.
namespace rayman2 {
    void frontend_init();
    void frontend_poll_input();
    bool frontend_get_input(int controller_num, uint16_t* buttons, float* x, float* y);
    void frontend_set_rumble(int controller_num, bool on);
    void frontend_handle_events();
    void frontend_shutdown();
}
#endif

// src/render_context.cpp
namespace rayman2 {
    std::unique_ptr<ultramodern::renderer::RendererContext>
    create_render_context(uint8_t* rdram,
                          ultramodern::renderer::WindowHandle window_handle,
                          bool developer_mode);
}

// RecompFrontend's ui_state.cpp declares `extern SDL_Window* window;` and
// expects the port to define it. The name is fixed by that declaration, so it
// is deliberately a plain global rather than something tidier in a namespace.
SDL_Window* window = nullptr;

// Defined at the bottom of this file, where the reason it cannot be static
// is explained. Declared here because the event pump below needs the game id.
extern std::vector<recomp::GameEntry> supported_games;

namespace {

// ---------------------------------------------------------------------------
// Game identity
// ---------------------------------------------------------------------------

// XXH3_64 of the supported dump, which is what librecomp checks a candidate ROM
// against. Rayman 2 (USA), NUS-NY2E rev 0, SHA-1
// 50558356b059ad3fbaf5fe95380512b9dceaaf52. See docs/PHASE00-FINDINGS.md.
constexpr uint64_t kRayman2UsaRomHash = 0x8b09d8d807f8dcbdULL;

// The port's own version, and the ONLY place it is written down.
//
// It reaches three things: the launcher, bottom-left, where librecomp renders
// it as major.minor.patch and the suffix does not show; the BUILD block at the
// top of every session report, via begin_session below; and the check mods are
// held to with minimum_recomp_version. src/debug_report.cpp used to carry its
// own copy of the string for the second of those, which is how a report comes
// to name a build that did not produce it.
const recomp::Version kProjectVersion{0, 2, 1, "-alpha"};

// ---------------------------------------------------------------------------
// Error reporting
// ---------------------------------------------------------------------------

// Every one of these is an error the player was shown, so every one of them
// belongs in the session report -- that is the whole point of the report: what
// the player saw and what the program saw, in one place and in order.
void message_box(const char* msg) {
    rayman2::report::error("message-box", "%s", msg);
    std::fprintf(stderr, "[rayman2] %s\n", msg);
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Rayman 2: Recompiled", msg, window);
}

// ---------------------------------------------------------------------------
// Graphics: the window RT64 attaches to
// ---------------------------------------------------------------------------

// Where this port keeps its settings, key bindings and the ingested ROM.
//
// librecomp defaults its config path to an empty path, which resolves against
// the process working directory. That is wrong in two ways at once: settings
// follow whatever directory the executable happened to be launched from, so
// they appear to reset; and an installed copy under Program Files cannot write
// there at all. Nothing sets it -- register_config_path exists and no part of
// the runtime or the frontend calls it -- so the port has to.
//
// The directory name is the program id registered with recompui, so the
// frontend and librecomp agree on one location.
std::filesystem::path app_folder_path() {
    std::filesystem::path base;
#ifdef _WIN32
    PWSTR known = nullptr;
    if (SUCCEEDED(SHGetKnownFolderPath(FOLDERID_RoamingAppData, 0, nullptr, &known))) {
        base = known;
        CoTaskMemFree(known);
    }
#elif defined(__APPLE__)
    if (const char* home = std::getenv("HOME")) {
        base = std::filesystem::path(home) / "Library" / "Application Support";
    }
#else
    if (const char* xdg = std::getenv("XDG_DATA_HOME")) {
        base = xdg;
    }
    else if (const char* home = std::getenv("HOME")) {
        base = std::filesystem::path(home) / ".local" / "share";
    }
#endif
    if (base.empty()) {
        // Last resort: the working directory, which is what the runtime would
        // have used anyway. Better than refusing to start.
        return std::filesystem::current_path();
    }
    return base / "rayman2-recomp";
}

// The directory the executable sits in. The debug reports go in a folder beside
// it, because that is where a player looking for them will look -- not in a
// per-user application data path they would have to be told about.
std::filesystem::path executable_directory() {
#ifdef _WIN32
    wchar_t buf[MAX_PATH] = {};
    const DWORD len = GetModuleFileNameW(nullptr, buf, MAX_PATH);
    if (len > 0 && len < MAX_PATH) {
        return std::filesystem::path(buf).parent_path();
    }
#endif
    return std::filesystem::current_path();
}

ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) != 0) {
        message_box(("SDL video init failed: " + std::string(SDL_GetError())).c_str());
        std::exit(EXIT_FAILURE);
    }
    return nullptr;
}

ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    // 800x600: 4:3, matching the game's own aspect, and small enough to sit on
    // a laptop screen without being dragged smaller on every launch. It is a
    // starting size, not a constraint -- the window is resizable and the
    // Graphics tab offers fullscreen.
    window = SDL_CreateWindow("Rayman 2: The Great Escape — Recompiled",
                                SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                800, 600,
                                SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
    if (window == nullptr) {
        message_box(("Failed to create window: " + std::string(SDL_GetError())).c_str());
        std::exit(EXIT_FAILURE);
    }

#ifdef _WIN32
    SDL_SysWMinfo wmInfo;
    SDL_VERSION(&wmInfo.version);
    SDL_GetWindowWMInfo(window, &wmInfo);
    return ultramodern::renderer::WindowHandle{ wmInfo.info.win.window, GetCurrentThreadId() };
#elif defined(__linux__)
    return window;
#else
    return ultramodern::renderer::WindowHandle{ window, nullptr };
#endif
}

// The Sound tab's Main Volume, as a linear gain.
//
// The frontend has always had the slider and the port has never read it: the
// tab is created in src/frontend.cpp, the value is written to sound.json, and
// nothing between there and SDL_QueueAudio ever looked at it. Moving it did
// nothing, which is what was reported.
//
// Published from the thread that pumps events and read on the thread that
// queues audio, so it is an atomic rather than a call to
// recompui::config::sound::get_main_volume() from the audio path -- the same
// shape src/draw_distance.cpp uses for the graphics settings, and for the same
// reason: the config store is the frontend's and is not documented as safe to
// read from anywhere.
//
// Linear, because the control is a percentage and that is what a percentage of
// volume most directly means. It is not a perceptual curve: 50 is half the
// amplitude, which is about six decibels down rather than half as loud.
std::atomic<float> g_audio_gain{1.0f};

#ifdef RAYMAN2_ENABLE_FRONTEND
// RAYMAN2_AUTOSTART=1 -- press Start on the launcher, so a run can be scripted.
//
// scripts/soak.sh needs the shipped configuration launched twenty times in a
// row, and the shipped configuration waits for somebody to click Start. Without
// this the only soakable build is the headless one, which is a different program
// in the ways that matter to docs/issues/003: it starts the game itself, on its
// own thread, with no frontend, no launcher and none of recompui's threads.
// Measuring that and reasoning about the other is how a bug survives a fix.
//
// It runs from the event pump rather than from a thread of its own, because
// that is the thread that owns the window and the UI: start_game is safe
// anywhere, hide_all_contexts is not, and the launcher itself calls both from
// exactly here. Waiting for the renderer's first frame is the same condition
// the non-frontend path waits on.
void maybe_autostart() {
    static const bool armed = std::getenv("RAYMAN2_AUTOSTART") != nullptr;
    if (!armed) {
        return;
    }
    static bool fired = false;
    if (fired || !rayman2::vi_has_ticked().load(std::memory_order_acquire)) {
        return;
    }
    fired = true;

    const std::u8string game_id = supported_games[0].game_id;
    if (!recomp::is_rom_valid(game_id)) {
        std::fprintf(stderr, "[rayman2] RAYMAN2_AUTOSTART: no ROM has been ingested yet;"
                             " run once by hand and choose it, then this will work\n");
        return;
    }
    std::fprintf(stderr, "[rayman2] RAYMAN2_AUTOSTART: starting the game without the launcher\n");
    recomp::start_game(game_id, {});
    recompui::hide_all_contexts();
}
#endif

// Pumps the OS event queue. Runs on the thread that created the window.
void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    // Keep the Aspect Ratio setting meaning "the game renders wide". Every
    // frame, because the frontend resets part of the graphics configuration
    // whenever any setting is applied. See src/draw_distance.cpp.
    if (window != nullptr) {
        int w = 0;
        int h = 0;
        SDL_GetWindowSize(window, &w, &h);
        rayman2::update_widescreen_policy(w, h);
    }

    // F9: capture everything worth having about the frame on screen. See
    // include/capture.h. This runs on the thread that pumps SDL events, which
    // is where the keyboard state is valid.
    rayman2::capture::poll_hotkey(g_rdram.load(std::memory_order_acquire));

    // Looks for the game's attract-mode flag. Off unless RAYMAN2_DEMOSCAN is set.
    rayman2::demo_scan_poll(g_rdram.load(std::memory_order_acquire));

    // Persist Controller Pak writes about once a second.
    //
    // This runs on the thread that pumps events rather than on the game thread,
    // which is the point: the game writes the pak from inside a blocking
    // libultra transaction, and doing file I/O there would put a disk write in
    // the middle of a transfer the game is timing. flush() is a cheap no-op
    // when nothing has changed, so the common case costs a comparison.
    {
        using clock = std::chrono::steady_clock;
        static clock::time_point next_flush{};
        const clock::time_point now = clock::now();
        if (now >= next_flush) {
            next_flush = now + std::chrono::seconds(1);
            rayman2::pak::flush();
        }
    }

#ifdef RAYMAN2_ENABLE_FRONTEND
    // Pick up the Sound tab's Main Volume. Every frame, for the same reason the
    // widescreen policy above is pushed every frame: the frontend rebuilds its
    // configuration whenever any setting is applied, and a value read once would
    // be a value that stopped tracking the slider the first time the player
    // touched anything.
    {
        const double percent = recompui::config::sound::get_main_volume();
        const float gain = static_cast<float>(percent) / 100.0f;
        g_audio_gain.store(gain < 0.0f ? 0.0f : (gain > 1.0f ? 1.0f : gain),
                           std::memory_order_relaxed);
    }

    maybe_autostart();
    rayman2::frontend_handle_events();
    return;
#else
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        switch (ev.type) {
            case SDL_QUIT:
                ultramodern::quit();
                break;
            default:
                break;
        }
    }
#endif
}

// ---------------------------------------------------------------------------
// Audio — SDL2 queued audio.
//
// The game has no sound yet: src/rsp.cpp reports audio tasks complete without
// synthesising anything, because Rayman 2's audio microcode has not been put
// through RSPRecomp (phase 05). This path is wired up regardless so that the
// device exists and the game's rate changes are honoured the moment the ucode
// lands, rather than being a second thing to debug then.
// ---------------------------------------------------------------------------

SDL_AudioDeviceID g_audio_device = 0;
uint32_t g_audio_frequency = 0;
constexpr int kBytesPerFrame = 2 * static_cast<int>(sizeof(int16_t));   // stereo s16

void set_frequency(uint32_t frequency) {
    if (frequency == g_audio_frequency) {
        return;
    }
    if (g_audio_device != 0) {
        SDL_CloseAudioDevice(g_audio_device);
        g_audio_device = 0;
    }

    // create_gfx only brings up SDL's video subsystem; audio is separate and is
    // initialised lazily here, the first time the game asks for a rate.
    if (SDL_WasInit(SDL_INIT_AUDIO) == 0) {
        if (SDL_InitSubSystem(SDL_INIT_AUDIO) != 0) {
            std::fprintf(stderr, "[rayman2] audio subsystem init failed: %s\n", SDL_GetError());
            return;
        }
    }

    SDL_AudioSpec desired{};
    desired.freq     = static_cast<int>(frequency);
    desired.format   = AUDIO_S16SYS;
    desired.channels = 2;
    desired.samples  = 1024;
    desired.callback = nullptr;                 // queued mode

    SDL_AudioSpec obtained{};
    g_audio_device = SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, 0);
    if (g_audio_device == 0) {
        std::fprintf(stderr, "[rayman2] audio device open failed: %s\n", SDL_GetError());
        return;
    }
    g_audio_frequency = frequency;
    SDL_PauseAudioDevice(g_audio_device, 0);
    std::fprintf(stderr, "[rayman2] audio device open: requested %u Hz, obtained %d Hz, %d ch\n",
                 frequency, obtained.freq, (int)obtained.channels);
}

size_t get_frames_remaining();

// Report the rate and the peak once a second while bringing audio up.
//
// "Samples are being queued" and "there is sound" are different claims: a
// microcode that runs to completion and writes silence produces exactly the
// same frame count as one that works. The peak distinguishes them, and it is
// the only part of the audio path that can be checked without listening.
//
// It measures what is actually QUEUED, after the volume has been applied, and
// reports the gain beside it. Measuring the game's buffer instead would be
// measuring the wrong end: the first version of the volume fix was tested with
// a probe that read the samples before they were scaled, so it reported
// identical peaks at 100, 50 and 0 and said nothing whatsoever about whether
// the volume worked.
void audio_probe(const int16_t* queued, size_t count, float gain) {
    static const bool on = std::getenv("RAYMAN2_AUDIOPROBE") != nullptr;
    if (!on) {
        return;
    }
    using clock = std::chrono::steady_clock;
    static clock::time_point last = clock::now();
    static uint64_t frames = 0;
    static int peak = 0;

    frames += count / 2;   // count is samples; report frames
    for (size_t i = 0; i < count; ++i) {
        const int v = queued[i] < 0 ? -queued[i] : queued[i];
        if (v > peak) peak = v;
    }

    const clock::time_point now = clock::now();
    if (now - last >= std::chrono::seconds(1)) {
        std::fprintf(stderr, "[rayman2] audio %llu frames/s  peak %d  gain %.2f  queued %zu\n",
                     (unsigned long long)frames, peak, static_cast<double>(gain),
                     get_frames_remaining());
        last = now; frames = 0; peak = 0;
    }
}

void queue_samples(int16_t* samples, size_t count) {

    // `count` is int16 samples, NOT stereo frames.
    //
    // The two audio callbacks use different units, which is easy to miss and
    // was: ultramodern's queue_audio_buffer computes
    // `sample_count = byte_count / sizeof(int16_t)` and passes that here, so it
    // counts each channel separately -- while get_frames_remaining below is
    // multiplied by `2 * sizeof(int16_t)` on the way back, so that one is
    // frames. Multiplying this by the bytes-per-frame queued twice as many
    // bytes as the game produced, which read past the buffer and made the
    // output queue grow by about sixteen thousand frames a second until the
    // sound was seconds behind the picture.
    if (g_audio_device == 0) {
        return;
    }

    const float gain = g_audio_gain.load(std::memory_order_relaxed);
    if (gain >= 0.999f) {
        audio_probe(samples, count, gain);
        SDL_QueueAudio(g_audio_device, samples,
                       static_cast<uint32_t>(count * sizeof(int16_t)));
        return;
    }

    // Scaled into scratch rather than in place: the buffer belongs to
    // ultramodern, and quietly rewriting a caller's samples is the kind of
    // thing that is fine until something else reads them too.
    //
    // No clamping is needed because the gain is never above one, so the product
    // cannot leave int16 range. Silence at zero is still queued rather than
    // skipped, so the output queue goes on being fed and get_frames_remaining
    // keeps meaning what it means.
    static thread_local std::vector<int16_t> scaled;
    scaled.resize(count);
    for (size_t i = 0; i < count; ++i) {
        scaled[i] = static_cast<int16_t>(static_cast<float>(samples[i]) * gain);
    }
    audio_probe(scaled.data(), scaled.size(), gain);
    SDL_QueueAudio(g_audio_device, scaled.data(),
                   static_cast<uint32_t>(scaled.size() * sizeof(int16_t)));
}

size_t get_frames_remaining() {
    if (g_audio_device == 0) {
        return 0;
    }
    return SDL_GetQueuedAudioSize(g_audio_device) / kBytesPerFrame;
}

// ---------------------------------------------------------------------------
// Input
//
// Port 1 reports a Controller Pak, because that is Rayman 2's only save medium
// (phase 00: 58 references, no EEPROM/SRAM/Flash). Pak::ControllerPak exists on
// this runtime fork specifically so a port can advertise an accessory that is
// not a Rumble Pak; the joybus READ_PAK/WRITE_PAK traffic is answered against
// the runtime's own backing store.
// ---------------------------------------------------------------------------

void poll_input() {
#ifdef RAYMAN2_ENABLE_FRONTEND
    rayman2::frontend_poll_input();
#else
    // SDL events are pumped in update_gfx; keyboard state is read directly below.
    SDL_PumpEvents();
#endif
}

bool get_input(int controller_num, uint16_t* buttons, float* x, float* y) {
#ifdef RAYMAN2_ENABLE_FRONTEND
    return rayman2::frontend_get_input(controller_num, buttons, x, y);
#else
    if (controller_num != 0) {
        return false;
    }

    const Uint8* keys = SDL_GetKeyboardState(nullptr);

    // Report the first call, and say whether SDL gave us a keyboard at all.
    //
    // Returning false here is not a quiet no-op: librecomp's
    // osContGetReadData_recomp only copies the pad into RDRAM when err_no is 0,
    // and err_no is only 0 when this returns true. So a null keyboard state
    // means the game's pad is never written and every button reads as released
    // -- indistinguishable, from inside the game, from a player sitting still.
    {
        static bool reported = false;
        if (!reported) {
            reported = true;
            std::fprintf(stderr, "[rayman2] first get_input: keyboard state %s\n",
                         keys == nullptr ? "NULL (no input will reach the game)" : "present");
        }
    }

    if (keys == nullptr) {
        return false;
    }

    uint16_t held = 0;
    auto set = [&](SDL_Scancode code, uint16_t mask) {
        if (keys[code]) {
            held |= mask;
        }
    };

    // A minimal keyboard map to get through boot and the menus. Remapping and
    // gamepads come with RecompFrontend's input tab in phase 06; this exists so
    // the game can be driven at all during bring-up.
    set(SDL_SCANCODE_X,      0x8000);   // A
    set(SDL_SCANCODE_C,      0x4000);   // B
    set(SDL_SCANCODE_Z,      0x2000);   // Z
    set(SDL_SCANCODE_RETURN, 0x1000);   // Start
    set(SDL_SCANCODE_UP,     0x0800);   // D-pad
    set(SDL_SCANCODE_DOWN,   0x0400);
    set(SDL_SCANCODE_LEFT,   0x0200);
    set(SDL_SCANCODE_RIGHT,  0x0100);
    set(SDL_SCANCODE_A,      0x0020);   // L
    set(SDL_SCANCODE_S,      0x0010);   // R

    float ax = 0.0f, ay = 0.0f;
    if (keys[SDL_SCANCODE_J]) ax -= 1.0f;
    if (keys[SDL_SCANCODE_L]) ax += 1.0f;
    if (keys[SDL_SCANCODE_I]) ay += 1.0f;
    if (keys[SDL_SCANCODE_K]) ay -= 1.0f;

    // Diagnostic: hold A and Start when RAYMAN2_AUTOPRESS is set.
    //
    // The bring-up runs launch the game and read its log, and nobody is at the
    // keyboard. That is fine until the game reaches a screen that waits for a
    // button, at which point "waiting for the player" and "hung" look exactly
    // the same from outside -- which is what happened: a loop polling for A or
    // Start read as a hang for several rounds of bisection.
    //
    // Holding the buttons is wrong for anything that wants an edge rather than
    // a level, so this is opt-in and never on by default.
    if (std::getenv("RAYMAN2_AUTOPRESS") != nullptr) {
        // Pulse rather than hold.
        //
        // The game does not test whether a button is down, it tests whether it
        // was newly pressed: func_800A3878 compares the current sample against
        // the previous entry in a ring and requires the bit to be absent there.
        // A permanently held button therefore produces exactly one edge, at
        // whatever moment sampling starts, and none afterwards -- so the first
        // version of this looked identical to no input at all.
        const auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                            std::chrono::steady_clock::now().time_since_epoch()).count();
        if ((ms / 250) % 2 == 0) {
            held |= 0x8000 | 0x1000;   // A and Start
        }
    }

    *buttons = held;
    *x = ax;
    *y = ay;
    return true;
#endif
}

void set_rumble(int controller_num, bool on) {
#ifdef RAYMAN2_ENABLE_FRONTEND
    rayman2::frontend_set_rumble(controller_num, on);
#else
    (void)controller_num; (void)on;
#endif
}

void set_rumble_unused(int, bool) {
    // No rumble: port 1 advertises a Controller Pak, not a Rumble Pak.
}

// Report a plain controller in port 1 and nothing in the others.
//
// This deliberately does NOT advertise a Controller Pak, and the reason is
// consistency rather than preference. What this returns feeds
// __osContGetInitData, which sets the status byte the game reads as "a pak is
// present"; but every Pfs entry point in librecomp answers PFS_ERR_NOPACK,
// which is the console's answer when the slot is empty. Claiming a pak here
// tells the game to go and use one that the runtime will then deny it, and a
// game that trusts its own query has no reason to give up -- it waits for a
// pak it has been told is there.
//
// Saying "no pak" is a state the shipped game had to handle, because a player
// can always run it without one. When the Pfs side is actually implemented,
// this is the line to change back, and the two must change together.
// What is plugged into each controller port.
//
// Port 1 has a controller with a Controller Pak in it; the other three are
// empty. ultramodern turns the pak field into OSContStatus.status -- bit 0,
// CONT_CARD_ON -- and Rayman 2 gates its whole save path on that bit, so
// reporting Pak::None here is enough on its own to produce "No Controller Pak
// found. The game will not be saved." however well the rest works.
//
// Reporting a Controller Pak deliberately gives up the Rumble Pak. ultramodern's
// osMotorInit answers PFS_ERR_DEVICE unless the reported pak is a Rumble Pak,
// which is the console's own behaviour: the controller has one slot, and a
// player who wants to save takes the Rumble Pak out. Serving both at once from
// the joybus layer is possible -- their address ranges do not overlap -- but it
// is a deviation from hardware, and saving is what was asked for.
ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    if (controller_num == 0) {
        return { ultramodern::input::Device::Controller,
                 rayman2::pak::present(0) ? ultramodern::input::Pak::ControllerPak
                                          : ultramodern::input::Pak::None };
    }
    return { ultramodern::input::Device::None, ultramodern::input::Pak::None };
}

// ---------------------------------------------------------------------------
// Threads
// ---------------------------------------------------------------------------

std::string get_game_thread_name(const OSThread* t) {
    return "rayman2-" + std::to_string(t ? t->id : 0);
}

bool select_and_report(const std::filesystem::path& path, const std::u8string& game_id) {
    switch (recomp::select_rom(path, game_id)) {
        case recomp::RomValidationError::Good:
            return true;
        case recomp::RomValidationError::FailedToOpen:
            message_box("Could not open that file.");
            return false;
        case recomp::RomValidationError::NotARom:
            message_box("That file is not an N64 ROM.");
            return false;
        case recomp::RomValidationError::IncorrectRom:
            message_box("That is an N64 ROM, but not Rayman 2 (USA).\n"
                        "This port targets NUS-NY2E rev 0, SHA-1 "
                        "50558356b059ad3fbaf5fe95380512b9dceaaf52.");
            return false;
        case recomp::RomValidationError::IncorrectVersion:
            message_box("That is Rayman 2, but not the USA revision this port targets.");
            return false;
        default:
            message_box("Could not read that ROM.");
            return false;
    }
}

} // namespace

// ---------------------------------------------------------------------------
// Game registration
//
// NOT in the anonymous namespace above, and not static: RecompFrontend's
// launcher declares `extern std::vector<recomp::GameEntry> supported_games;`
// and links against this definition to list the game and drive its own
// "Load ROM" flow. Giving it internal linkage builds fine and fails at link
// with one undefined symbol and no hint as to why.
// ---------------------------------------------------------------------------

std::vector<recomp::GameEntry> supported_games = {
    recomp::GameEntry{
        .rom_hash      = kRayman2UsaRomHash,
        .internal_name = "RAYMAN 2",
        .display_name  = "Rayman 2: The Great Escape",
        .game_id       = u8"rayman2_us",
        .mod_game_id   = "rayman2",
        // The cartridge has no EEPROM, SRAM or Flash. Saves go to a Controller
        // Pak, which is an input-side accessory rather than a cartridge save
        // type, so the save type here is genuinely None.
        .save_type     = recomp::SaveType::None,
        .is_enabled    = true,
        // MUST be sign-extended. `gpr` is 64-bit, and every MIPS address the
        // runtime handles is a sign-extended 32-bit value: KSEG0 0x80000400 is
        // 0xFFFFFFFF80000400, not 0x0000000080000400.
        //
        // Writing the bare literal here cost a long debugging session. MEM_B
        // resolves a game address as rdram + (addr ^ 3) - 0xFFFFFFFF80000000,
        // so a zero-extended entrypoint yields offset 0x100000403 instead of
        // 0x403 -- exactly 0x1_00000000 too far, past the end of the 4 GB RDRAM
        // reservation and into unmapped space. librecomp's emulated IPL3 DMA
        // then wrote there and took an access violation four bytes into the
        // copy, three frames deep in the runtime, long before the entrypoint.
        //
        // N64Recomp's own generated lookup.cpp writes the same constant as
        // (gpr)(int32_t)0x80000400u for this reason; this must match it.
        .entrypoint_address = (gpr)(int32_t)0x80000400u,
        .entrypoint         = rayman2_entrypoint,
    },
};


int main(int argc, char** argv) {
    // Unbuffered, because the failure mode being chased here is a fail-fast
    // exit (0xC0000409) that discards anything still sitting in a buffer.
    std::setvbuf(stderr, nullptr, _IONBF, 0);
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    // Open this session's debug report before the first line is printed, so
    // that everything from here on -- the port's own output, librecomp's and
    // RT64's -- is mirrored into it, and so the crash reporter installed below
    // has somewhere to write.
    rayman2::report::begin_session(executable_directory(), app_folder_path(),
                                   kProjectVersion.to_string());

    std::fprintf(stderr, "[rayman2] start\n");
    if (!rayman2::report::path().empty()) {
        std::fprintf(stderr, "[rayman2] debug report: %s\n",
                     rayman2::report::path().string().c_str());
    }

    // Installed before anything else: the fault being chased happens on a
    // renderer thread and otherwise produces no output at all.
    rayman2_install_crash_reporter();

    // Prove the crash reporting works, on demand.
    //
    // Crash handling is the one feature that cannot be verified by using the
    // program normally: it only runs when something has already gone wrong, and
    // a reporter that is silently broken looks exactly like a session with no
    // crashes in it. RAYMAN2_SELFTEST=crash raises an access violation and
    // RAYMAN2_SELFTEST=terminate throws through a noexcept boundary, which are
    // the two paths -- the unhandled-exception filter and std::terminate --
    // that write a crash block. Neither can fire by accident.
    if (const char* selftest = std::getenv("RAYMAN2_SELFTEST")) {
        if (std::strcmp(selftest, "crash") == 0) {
            std::fprintf(stderr, "[rayman2] self-test: raising an access violation\n");
            *reinterpret_cast<volatile int*>(0) = 1;
        }
        else if (std::strcmp(selftest, "terminate") == 0) {
            std::fprintf(stderr, "[rayman2] self-test: throwing through noexcept\n");
            []() noexcept { throw std::runtime_error("debug report self-test"); }();
        }
        // The third path, and the one that was missing when it was needed.
        //
        // A null indirect call in the recompiled game used to print one line
        // into a pipe and call std::exit from a game thread, and the teardown
        // that followed crashed and reported ITSELF. The handler that replaces
        // it is in src/crash_report.cpp; this is how to see it work without
        // waiting for the game to do it. See docs/issues/003.
        else if (std::strcmp(selftest, "nullcall") == 0) {
            std::fprintf(stderr, "[rayman2] self-test: looking up a function at 0x00000000\n");
            get_function(0);
        }
    }

    SDL_SetMainReady();

#ifdef _WIN32
    timeBeginPeriod(1);   // 1 ms scheduler granularity; the runtime sleeps in small slices
#endif

    // Controllers.
    //
    // Nothing else initialises this. SDL only enumerates game controllers, and
    // only emits SDL_CONTROLLERDEVICEADDED, once its game-controller subsystem
    // is up -- and the port was initialising only video and audio. recompinput
    // handles the ADDED event correctly and opens the device, so a wired pad
    // was not "unsupported" so much as never announced: no event, no open, no
    // input, and no error either.
    //
    // It has to happen before the frontend is initialised, because SDL queues
    // an ADDED event for every device already attached at the moment the
    // subsystem starts, and those are what populate the controller profiles.
    if (SDL_InitSubSystem(SDL_INIT_GAMECONTROLLER) != 0) {
        rayman2::report::error("input", "SDL game controller init failed: %s", SDL_GetError());
        std::fprintf(stderr, "[rayman2] no game controller support: %s\n", SDL_GetError());
    }

    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    rayman2_register_sections();

    // ---- ROM ----
    // A ROM validated on a previous run and cached in the config directory wins;
    // otherwise an explicit path argument is validated and cached. The player is
    // only ever asked once.
    const std::u8string game_id = supported_games[0].game_id;
    // Must precede check_all_stored_roms() and, with the frontend,
    // frontend_init(): the first looks for the ingested ROM under this path and
    // the second loads the saved key bindings from it.
    {
        std::error_code ec;
        const std::filesystem::path cfg = app_folder_path();
        std::filesystem::create_directories(cfg, ec);
        recomp::register_config_path(cfg);
        // The Controller Pak images live beside the rest of the configuration.
        // This has to happen before the game starts, because the first thing it
        // does with the pak is read it.
        rayman2::pak::set_storage_directory(cfg);
        // Captures land beside the session reports, so a player who has found
        // one has found the other.
        rayman2::capture::set_output_directory(
            rayman2::report::path().empty() ? cfg : rayman2::report::path().parent_path());
        rayman2::report::add_context("config directory", cfg.string());
        std::fprintf(stderr, "[rayman2] config path: %s\n", cfg.string().c_str());
    }

    recomp::check_all_stored_roms();
    bool have_rom = recomp::is_rom_valid(game_id);
    rayman2::report::add_context("rom",
        have_rom ? "a validated dump is stored in the config directory"
                 : "none stored yet -- the launcher will ask for one");

    if (!have_rom && argc > 1) {
        have_rom = select_and_report(std::filesystem::path(argv[1]), game_id);
    }

#ifndef RAYMAN2_ENABLE_FRONTEND
    if (!have_rom) {
        message_box("No ROM configured. Pass the path to your Rayman 2 (USA) dump "
                    "as the first argument.");
        return EXIT_FAILURE;
    }

    // Without the frontend there is no launcher to start the game, so do it
    // here once the runtime is up. With the frontend, its launcher owns this
    // decision and starting from here would race it.
    // Wait for the renderer's first frame, not a fixed delay.
    //
    // ultramodern's VI thread only seeds a dummy video mode while the game has
    // not started; starting the game before its first tick makes the VI update
    // path dereference a mode that does not exist yet. A sleep here raced that
    // and lost about nine times in ten -- an access violation before librecomp
    // even initialised its heap, with the successful tenth run being the only
    // one that looked like progress.
    std::thread([game_id]() {
        using namespace std::chrono_literals;
        for (int i = 0; i < 1000 && !rayman2::vi_has_ticked().load(std::memory_order_acquire); ++i) {
            std::this_thread::sleep_for(10ms);
        }
        if (!rayman2::vi_has_ticked().load(std::memory_order_acquire)) {
            std::fprintf(stderr, "[rayman2] renderer never presented a frame; starting anyway\n");
        }
        // Load the cached ROM into memory before starting.
        //
        // This is NOT the same thing as validating it. check_all_stored_roms()
        // and is_rom_valid() only establish that a correct dump exists in the
        // config directory; they do not read it. Nothing else does either --
        // start_game() does not, and the port is expected to.
        //
        // Skipping it is not a quiet no-op. librecomp's init() emulates IPL3
        // with a fixed 1 MB DMA from ROM into RDRAM, and do_rom_read() computes
        // its source as rom.data() + physical_addr - rom_base. With an empty
        // span that is an offset from nullptr, and the copy walks into
        // unmapped memory -- an access violation on the game thread, three
        // frames deep in the runtime, with nothing pointing back at the real
        // mistake up here.
        if (!recomp::load_stored_rom(game_id)) {
            message_box("Failed to load the stored ROM from the config directory.");
            return;
        }
        std::fprintf(stderr, "[rayman2] rom loaded: %zu bytes\n",
                     recomp::get_rom().size());

        recomp::start_game(game_id, "");
    }).detach();
#else
    (void)have_rom;
#endif

    // ---- Callbacks ----
    recomp::rsp::callbacks_t rsp_callbacks{};                    // mandatory
    rsp_callbacks.get_rsp_microcode = rayman2_get_rsp_microcode;

    ultramodern::renderer::callbacks_t renderer_callbacks{};     // mandatory
    renderer_callbacks.create_render_context = rayman2::create_render_context;

    ultramodern::gfx_callbacks_t gfx_callbacks{};
    gfx_callbacks.create_gfx    = create_gfx;
    gfx_callbacks.create_window = create_window;
    gfx_callbacks.update_gfx    = update_gfx;

    ultramodern::audio_callbacks_t audio_callbacks{};
    audio_callbacks.queue_samples        = queue_samples;
    audio_callbacks.get_frames_remaining = get_frames_remaining;
    audio_callbacks.set_frequency        = set_frequency;

    ultramodern::input::callbacks_t input_callbacks{};
    input_callbacks.poll_input                = poll_input;
    input_callbacks.get_input                 = get_input;
    input_callbacks.set_rumble                = set_rumble;
    input_callbacks.get_connected_device_info = get_connected_device_info;

    ultramodern::error_handling::callbacks_t error_handling_callbacks{};
    error_handling_callbacks.message_box = message_box;

    ultramodern::threads::callbacks_t threads_callbacks{};
    threads_callbacks.get_game_thread_name = get_game_thread_name;

    // Install the message-queue control, which nothing installs by default.
    //
    // ultramodern delivers VI retrace, RSP and RDP completion, PI and SI from
    // outside the game threads, through a queue drained inside osSendMesg,
    // osRecvMesg and osJamMesg. When a delivery finds the destination queue
    // momentarily full it either puts the message back or throws it away, and
    // which of those it does comes from a bitset configured by this call.
    //
    // Nothing calls it -- not the port, and not ultramodern itself -- so that
    // bitset is default-constructed, every bit clear, and every source is
    // "throw it away". For most sources that is survivable, because another
    // message follows: VI retrace comes again in sixteen milliseconds.
    //
    // For the RDP it is fatal. Rayman 2's frame loop is a strict handshake with
    // exactly one message per frame: the producer takes the single free
    // framebuffer slot, builds a display list and posts it; the task thread
    // submits it; the RDP finishes; the completion message returns the slot.
    // Lose that message once and there is never another, because the next one
    // is only generated by the frame that the lost message was supposed to
    // allow. The observed behaviour matched exactly -- one display list, ever.
    //
    // The struct's own defaults are the intended policy (requeue timer, RSP, SI
    // and RDP; drop VI, AI and PI), so passing a default-constructed one is
    // both the fix and a statement of what the port wants.
    ultramodern::set_message_queue_control(ultramodern::MessageQueueControl{});

    // Make the RDP appear to take time. Without this the game's frame loop --
    // a handshake that blocks until the RDP reports finished -- is paced by
    // nothing at all and runs at twice its intended speed. docs/issues/004.
    rayman2::install_frame_pacing();

    recomp::Configuration config{};
    config.argc                     = argc;
    config.argv                     = argv;
    config.project_version          = kProjectVersion;
    config.rsp_callbacks            = rsp_callbacks;
    config.renderer_callbacks       = renderer_callbacks;
    config.audio_callbacks          = audio_callbacks;
    config.input_callbacks          = input_callbacks;
    config.gfx_callbacks            = gfx_callbacks;
    config.error_handling_callbacks = error_handling_callbacks;
    config.threads_callbacks        = threads_callbacks;

#ifdef RAYMAN2_ENABLE_FRONTEND
    // Program identity and menu layout must be registered before recomp::start()
    // brings the renderer up: recompui builds its menus during that bring-up.
    // The id is the directory name the frontend stores settings and saves under,
    // so it is part of the port's on-disk contract and should not drift.
    recompui::programconfig::set_program_id(u8"rayman2-recomp");
    recompui::programconfig::set_program_name("Rayman 2: The Great Escape");

    // Mandatory. recompui throws std::runtime_error during renderer bring-up if
    // no primary font has been registered by the time it builds its menus, and
    // that exception crosses a noexcept boundary -- the process fail-fasts with
    // no output whatsoever, which is a memorably unhelpful way to learn this.
    // The family name is the font's internal one, not its filename.
    recompui::register_primary_font("LatoLatin-Regular.ttf", "LatoLatin");
    recompui::register_extra_font("NotoEmoji-Regular.ttf");

    // Default bindings and the config tabs, then finalize(). recompui builds
    // its menus inside RT64 setup and the config modal throws if no
    // configuration has been loaded, so this cannot wait until after start().
    // See src/frontend.cpp.
    rayman2::frontend_init();
#endif

    // recomp::start() brings up the renderer, and the frontend builds its menus
    // during that bring-up. Anything thrown in there crosses a noexcept
    // boundary on its way out and the process fail-fasts with no message, so
    // the exception is caught and reported here instead of being guessed at.
    rayman2_start_thread_sampler();

    std::fprintf(stderr, "[rayman2] entering recomp::start\n");
    try {
        recomp::start(config);   // blocks until the game exits
    }
    catch (const std::exception& e) {
        std::fprintf(stderr, "[rayman2] FATAL: %s\n", e.what());
        return EXIT_FAILURE;
    }
    catch (...) {
        std::fprintf(stderr, "[rayman2] FATAL: unknown exception\n");
        return EXIT_FAILURE;
    }
    rayman2_stop_thread_sampler();

    // Persist what the session changed.
    //
    // Both of these have a saving path of their own during play -- the pak
    // flushes on a timer in update_gfx, and the Controls tab writes its
    // bindings when it closes -- so this is the pass that catches a player who
    // changed something and then quit without closing the menu, and the last
    // second of pak writes before the window went away.
    rayman2::pak::flush();
#ifdef RAYMAN2_ENABLE_FRONTEND
    rayman2::frontend_shutdown();
#endif
    std::fprintf(stderr, "[rayman2] recomp::start returned\n");

#ifdef _WIN32
    timeEndPeriod(1);
#endif

    // Closes the report with its summary. A report without one was killed or
    // crashed hard, which is a fact worth being able to read off the file.
    rayman2::report::end_session(true);
    return EXIT_SUCCESS;
}

// The renderer wrapper in src/render_context.cpp needs RDRAM on the graphics
// thread, and the gfx callbacks carry no rdram argument. Defined down here
// rather than beside g_rdram so that nothing about the file's namespace
// structure has to move to accommodate it.
namespace rayman2 {
    uint8_t* rdram_base() {
        return g_rdram.load(std::memory_order_acquire);
    }
}
