// rayman-2-the-great-escape-recomp — runtime host.
//
// Brings up the pieces the recompiled game needs and hands control to
// librecomp: an SDL window for RT64 to attach to, audio and input callbacks,
// and the game entry that ties the player's ROM to the recompiled entrypoint.
//
// Written against THIS repository's pinned runtime (lib/N64ModernRuntime, the
// controller-pak branch). Every callback signature below was read out of the
// vendored headers rather than assumed, because they differ between forks.

#include <atomic>
#include <chrono>
#include <cstdint>
#include <cstdio>
#include <exception>
#include <cstdlib>
#include <filesystem>
#include <memory>
#include <string>
#include <thread>
#include <vector>

#include "ultramodern/ultramodern.hpp"
#include "ultramodern/renderer_context.hpp"
#include "ultramodern/error_handling.hpp"
#include "ultramodern/input.hpp"
#include "ultramodern/threads.hpp"

#include "librecomp/game.hpp"
#include "librecomp/rsp.hpp"

#define SDL_MAIN_HANDLED
#include <SDL.h>
#ifdef _WIN32
#include <SDL_syswm.h>   // SDL_GetWindowWMInfo -> native HWND.
                         // Windows only: on Linux the WindowHandle IS the
                         // SDL_Window*, and this header drags in <X11/X.h>,
                         // whose `None` macro collides with enumerators such as
                         // Device::None and Pak::None.
#include <timeapi.h>     // timeBeginPeriod; links winmm
#endif

#ifdef RAYMAN2_ENABLE_FRONTEND
#include "recompui/recompui.h"
#include "recompui/program_config.h"   // recompui::programconfig::set_program_*
#endif

// ---------------------------------------------------------------------------
// Generated by N64Recomp into RecompiledFuncs/. Declared, never defined here.
// ---------------------------------------------------------------------------
extern "C" void recomp_entrypoint(uint8_t* rdram, recomp_context* ctx);

// The game's entry point, wrapped so that crossing into recompiled code is
// visible in the log. This is the phase 03 gate: everything before it is host
// setup, everything after it is Rayman 2's own code running.
extern "C" void rayman2_entrypoint(uint8_t* rdram, recomp_context* ctx) {
    std::fprintf(stderr, "[rayman2] entering recomp_entrypoint -- the game thread is running\n");
    recomp_entrypoint(rdram, ctx);
    std::fprintf(stderr, "[rayman2] recomp_entrypoint returned\n");
}
gpr get_entrypoint_address();

// src/rsp.cpp
RspUcodeFunc* rayman2_get_rsp_microcode(const OSTask* task);

// src/register_sections.cpp — hands N64Recomp's section tables to librecomp so
// game-side addresses can be resolved back to recompiled functions.
void rayman2_register_sections();

// src/crash_report.cpp -- prints a located fault instead of exiting silently.
void rayman2_install_crash_reporter();

// src/thread_sampler.cpp -- opt-in (RAYMAN2_SAMPLE) profile of where the
// game's threads actually are, for when nothing crashes and nothing draws.
void rayman2_start_thread_sampler();
void rayman2_stop_thread_sampler();

// src/rt64_context.cpp -- set true once the renderer has presented a frame.
namespace rayman2 { std::atomic<bool>& vi_has_ticked(); }

// src/render_context.cpp
namespace rayman2 {
    std::unique_ptr<ultramodern::renderer::RendererContext>
    create_render_context(uint8_t* rdram,
                          ultramodern::renderer::WindowHandle window_handle,
                          bool developer_mode);
}

// RecompFrontend's ui_state.cpp declares `extern SDL_Window* window;` and
// expects the port to define it. The name is fixed by that declaration, so it
// is deliberately a plain global rather than something tidier in a namespace.
SDL_Window* window = nullptr;

namespace {

// ---------------------------------------------------------------------------
// Game identity
// ---------------------------------------------------------------------------

// XXH3_64 of the supported dump, which is what librecomp checks a candidate ROM
// against. Rayman 2 (USA), NUS-NY2E rev 0, SHA-1
// 50558356b059ad3fbaf5fe95380512b9dceaaf52. See docs/PHASE00-FINDINGS.md.
constexpr uint64_t kRayman2UsaRomHash = 0x8b09d8d807f8dcbdULL;

const recomp::Version kProjectVersion{0, 3, 0};

// ---------------------------------------------------------------------------
// Error reporting
// ---------------------------------------------------------------------------

void message_box(const char* msg) {
    std::fprintf(stderr, "[rayman2] %s\n", msg);
    SDL_ShowSimpleMessageBox(SDL_MESSAGEBOX_ERROR, "Rayman 2: Recompiled", msg, window);
}

// ---------------------------------------------------------------------------
// Graphics: the window RT64 attaches to
// ---------------------------------------------------------------------------

ultramodern::gfx_callbacks_t::gfx_data_t create_gfx() {
    if (SDL_InitSubSystem(SDL_INIT_VIDEO) != 0) {
        message_box(("SDL video init failed: " + std::string(SDL_GetError())).c_str());
        std::exit(EXIT_FAILURE);
    }
    return nullptr;
}

ultramodern::renderer::WindowHandle create_window(ultramodern::gfx_callbacks_t::gfx_data_t) {
    window = SDL_CreateWindow("Rayman 2: The Great Escape — Recompiled",
                                SDL_WINDOWPOS_CENTERED, SDL_WINDOWPOS_CENTERED,
                                1280, 960,
                                SDL_WINDOW_RESIZABLE | SDL_WINDOW_ALLOW_HIGHDPI);
    if (window == nullptr) {
        message_box(("Failed to create window: " + std::string(SDL_GetError())).c_str());
        std::exit(EXIT_FAILURE);
    }

#ifdef _WIN32
    SDL_SysWMinfo wmInfo;
    SDL_VERSION(&wmInfo.version);
    SDL_GetWindowWMInfo(window, &wmInfo);
    return ultramodern::renderer::WindowHandle{ wmInfo.info.win.window, GetCurrentThreadId() };
#elif defined(__linux__)
    return window;
#else
    return ultramodern::renderer::WindowHandle{ window, nullptr };
#endif
}

// Pumps the OS event queue. Runs on the thread that created the window.
void update_gfx(ultramodern::gfx_callbacks_t::gfx_data_t) {
    SDL_Event ev;
    while (SDL_PollEvent(&ev)) {
        switch (ev.type) {
            case SDL_QUIT:
                ultramodern::quit();
                break;
            default:
                break;
        }
    }
}

// ---------------------------------------------------------------------------
// Audio — SDL2 queued audio.
//
// The game has no sound yet: src/rsp.cpp reports audio tasks complete without
// synthesising anything, because Rayman 2's audio microcode has not been put
// through RSPRecomp (phase 05). This path is wired up regardless so that the
// device exists and the game's rate changes are honoured the moment the ucode
// lands, rather than being a second thing to debug then.
// ---------------------------------------------------------------------------

SDL_AudioDeviceID g_audio_device = 0;
uint32_t g_audio_frequency = 0;
constexpr int kBytesPerFrame = 2 * static_cast<int>(sizeof(int16_t));   // stereo s16

void set_frequency(uint32_t frequency) {
    if (frequency == g_audio_frequency) {
        return;
    }
    if (g_audio_device != 0) {
        SDL_CloseAudioDevice(g_audio_device);
        g_audio_device = 0;
    }

    // create_gfx only brings up SDL's video subsystem; audio is separate and is
    // initialised lazily here, the first time the game asks for a rate.
    if (SDL_WasInit(SDL_INIT_AUDIO) == 0) {
        if (SDL_InitSubSystem(SDL_INIT_AUDIO) != 0) {
            std::fprintf(stderr, "[rayman2] audio subsystem init failed: %s\n", SDL_GetError());
            return;
        }
    }

    SDL_AudioSpec desired{};
    desired.freq     = static_cast<int>(frequency);
    desired.format   = AUDIO_S16SYS;
    desired.channels = 2;
    desired.samples  = 1024;
    desired.callback = nullptr;                 // queued mode

    SDL_AudioSpec obtained{};
    g_audio_device = SDL_OpenAudioDevice(nullptr, 0, &desired, &obtained, 0);
    if (g_audio_device == 0) {
        std::fprintf(stderr, "[rayman2] audio device open failed: %s\n", SDL_GetError());
        return;
    }
    g_audio_frequency = frequency;
    SDL_PauseAudioDevice(g_audio_device, 0);
}

void queue_samples(int16_t* samples, size_t count) {
    if (g_audio_device != 0) {
        SDL_QueueAudio(g_audio_device, samples, static_cast<uint32_t>(count * kBytesPerFrame));
    }
}

size_t get_frames_remaining() {
    if (g_audio_device == 0) {
        return 0;
    }
    return SDL_GetQueuedAudioSize(g_audio_device) / kBytesPerFrame;
}

// ---------------------------------------------------------------------------
// Input
//
// Port 1 reports a Controller Pak, because that is Rayman 2's only save medium
// (phase 00: 58 references, no EEPROM/SRAM/Flash). Pak::ControllerPak exists on
// this runtime fork specifically so a port can advertise an accessory that is
// not a Rumble Pak; the joybus READ_PAK/WRITE_PAK traffic is answered against
// the runtime's own backing store.
// ---------------------------------------------------------------------------

void poll_input() {
    // SDL events are pumped in update_gfx; keyboard state is read directly below.
    SDL_PumpEvents();
}

bool get_input(int controller_num, uint16_t* buttons, float* x, float* y) {
    if (controller_num != 0) {
        return false;
    }

    const Uint8* keys = SDL_GetKeyboardState(nullptr);

    // Report the first call, and say whether SDL gave us a keyboard at all.
    //
    // Returning false here is not a quiet no-op: librecomp's
    // osContGetReadData_recomp only copies the pad into RDRAM when err_no is 0,
    // and err_no is only 0 when this returns true. So a null keyboard state
    // means the game's pad is never written and every button reads as released
    // -- indistinguishable, from inside the game, from a player sitting still.
    {
        static bool reported = false;
        if (!reported) {
            reported = true;
            std::fprintf(stderr, "[rayman2] first get_input: keyboard state %s\n",
                         keys == nullptr ? "NULL (no input will reach the game)" : "present");
        }
    }

    if (keys == nullptr) {
        return false;
    }

    uint16_t held = 0;
    auto set = [&](SDL_Scancode code, uint16_t mask) {
        if (keys[code]) {
            held |= mask;
        }
    };

    // A minimal keyboard map to get through boot and the menus. Remapping and
    // gamepads come with RecompFrontend's input tab in phase 06; this exists so
    // the game can be driven at all during bring-up.
    set(SDL_SCANCODE_X,      0x8000);   // A
    set(SDL_SCANCODE_C,      0x4000);   // B
    set(SDL_SCANCODE_Z,      0x2000);   // Z
    set(SDL_SCANCODE_RETURN, 0x1000);   // Start
    set(SDL_SCANCODE_UP,     0x0800);   // D-pad
    set(SDL_SCANCODE_DOWN,   0x0400);
    set(SDL_SCANCODE_LEFT,   0x0200);
    set(SDL_SCANCODE_RIGHT,  0x0100);
    set(SDL_SCANCODE_A,      0x0020);   // L
    set(SDL_SCANCODE_S,      0x0010);   // R

    float ax = 0.0f, ay = 0.0f;
    if (keys[SDL_SCANCODE_J]) ax -= 1.0f;
    if (keys[SDL_SCANCODE_L]) ax += 1.0f;
    if (keys[SDL_SCANCODE_I]) ay += 1.0f;
    if (keys[SDL_SCANCODE_K]) ay -= 1.0f;

    // Diagnostic: hold A and Start when RAYMAN2_AUTOPRESS is set.
    //
    // The bring-up runs launch the game and read its log, and nobody is at the
    // keyboard. That is fine until the game reaches a screen that waits for a
    // button, at which point "waiting for the player" and "hung" look exactly
    // the same from outside -- which is what happened: a loop polling for A or
    // Start read as a hang for several rounds of bisection.
    //
    // Holding the buttons is wrong for anything that wants an edge rather than
    // a level, so this is opt-in and never on by default.
    if (std::getenv("RAYMAN2_AUTOPRESS") != nullptr) {
        // Pulse rather than hold.
        //
        // The game does not test whether a button is down, it tests whether it
        // was newly pressed: func_800A3878 compares the current sample against
        // the previous entry in a ring and requires the bit to be absent there.
        // A permanently held button therefore produces exactly one edge, at
        // whatever moment sampling starts, and none afterwards -- so the first
        // version of this looked identical to no input at all.
        const auto ms = std::chrono::duration_cast<std::chrono::milliseconds>(
                            std::chrono::steady_clock::now().time_since_epoch()).count();
        if ((ms / 250) % 2 == 0) {
            held |= 0x8000 | 0x1000;   // A and Start
        }
    }

    *buttons = held;
    *x = ax;
    *y = ay;
    return true;
}

void set_rumble(int, bool) {
    // No rumble: port 1 advertises a Controller Pak, not a Rumble Pak.
}

// Report a plain controller in port 1 and nothing in the others.
//
// This deliberately does NOT advertise a Controller Pak, and the reason is
// consistency rather than preference. What this returns feeds
// __osContGetInitData, which sets the status byte the game reads as "a pak is
// present"; but every Pfs entry point in librecomp answers PFS_ERR_NOPACK,
// which is the console's answer when the slot is empty. Claiming a pak here
// tells the game to go and use one that the runtime will then deny it, and a
// game that trusts its own query has no reason to give up -- it waits for a
// pak it has been told is there.
//
// Saying "no pak" is a state the shipped game had to handle, because a player
// can always run it without one. When the Pfs side is actually implemented,
// this is the line to change back, and the two must change together.
ultramodern::input::connected_device_info_t get_connected_device_info(int controller_num) {
    if (controller_num == 0) {
        return { ultramodern::input::Device::Controller,
                 ultramodern::input::Pak::None };
    }
    return { ultramodern::input::Device::None, ultramodern::input::Pak::None };
}

// ---------------------------------------------------------------------------
// Threads
// ---------------------------------------------------------------------------

std::string get_game_thread_name(const OSThread* t) {
    return "rayman2-" + std::to_string(t ? t->id : 0);
}

bool select_and_report(const std::filesystem::path& path, const std::u8string& game_id) {
    switch (recomp::select_rom(path, game_id)) {
        case recomp::RomValidationError::Good:
            return true;
        case recomp::RomValidationError::FailedToOpen:
            message_box("Could not open that file.");
            return false;
        case recomp::RomValidationError::NotARom:
            message_box("That file is not an N64 ROM.");
            return false;
        case recomp::RomValidationError::IncorrectRom:
            message_box("That is an N64 ROM, but not Rayman 2 (USA).\n"
                        "This port targets NUS-NY2E rev 0, SHA-1 "
                        "50558356b059ad3fbaf5fe95380512b9dceaaf52.");
            return false;
        case recomp::RomValidationError::IncorrectVersion:
            message_box("That is Rayman 2, but not the USA revision this port targets.");
            return false;
        default:
            message_box("Could not read that ROM.");
            return false;
    }
}

} // namespace

// ---------------------------------------------------------------------------
// Game registration
//
// NOT in the anonymous namespace above, and not static: RecompFrontend's
// launcher declares `extern std::vector<recomp::GameEntry> supported_games;`
// and links against this definition to list the game and drive its own
// "Load ROM" flow. Giving it internal linkage builds fine and fails at link
// with one undefined symbol and no hint as to why.
// ---------------------------------------------------------------------------

std::vector<recomp::GameEntry> supported_games = {
    recomp::GameEntry{
        .rom_hash      = kRayman2UsaRomHash,
        .internal_name = "RAYMAN 2",
        .display_name  = "Rayman 2: The Great Escape",
        .game_id       = u8"rayman2_us",
        .mod_game_id   = "rayman2",
        // The cartridge has no EEPROM, SRAM or Flash. Saves go to a Controller
        // Pak, which is an input-side accessory rather than a cartridge save
        // type, so the save type here is genuinely None.
        .save_type     = recomp::SaveType::None,
        .is_enabled    = true,
        // MUST be sign-extended. `gpr` is 64-bit, and every MIPS address the
        // runtime handles is a sign-extended 32-bit value: KSEG0 0x80000400 is
        // 0xFFFFFFFF80000400, not 0x0000000080000400.
        //
        // Writing the bare literal here cost a long debugging session. MEM_B
        // resolves a game address as rdram + (addr ^ 3) - 0xFFFFFFFF80000000,
        // so a zero-extended entrypoint yields offset 0x100000403 instead of
        // 0x403 -- exactly 0x1_00000000 too far, past the end of the 4 GB RDRAM
        // reservation and into unmapped space. librecomp's emulated IPL3 DMA
        // then wrote there and took an access violation four bytes into the
        // copy, three frames deep in the runtime, long before the entrypoint.
        //
        // N64Recomp's own generated lookup.cpp writes the same constant as
        // (gpr)(int32_t)0x80000400u for this reason; this must match it.
        .entrypoint_address = (gpr)(int32_t)0x80000400u,
        .entrypoint         = rayman2_entrypoint,
    },
};


int main(int argc, char** argv) {
    // Unbuffered, because the failure mode being chased here is a fail-fast
    // exit (0xC0000409) that discards anything still sitting in a buffer.
    std::setvbuf(stderr, nullptr, _IONBF, 0);
    std::setvbuf(stdout, nullptr, _IONBF, 0);
    std::fprintf(stderr, "[rayman2] start\n");

    // Installed before anything else: the fault being chased happens on a
    // renderer thread and otherwise produces no output at all.
    rayman2_install_crash_reporter();

    SDL_SetMainReady();

#ifdef _WIN32
    timeBeginPeriod(1);   // 1 ms scheduler granularity; the runtime sleeps in small slices
#endif

    for (const auto& game : supported_games) {
        recomp::register_game(game);
    }

    rayman2_register_sections();

    // ---- ROM ----
    // A ROM validated on a previous run and cached in the config directory wins;
    // otherwise an explicit path argument is validated and cached. The player is
    // only ever asked once.
    const std::u8string game_id = supported_games[0].game_id;
    recomp::check_all_stored_roms();
    bool have_rom = recomp::is_rom_valid(game_id);

    if (!have_rom && argc > 1) {
        have_rom = select_and_report(std::filesystem::path(argv[1]), game_id);
    }

#ifndef RAYMAN2_ENABLE_FRONTEND
    if (!have_rom) {
        message_box("No ROM configured. Pass the path to your Rayman 2 (USA) dump "
                    "as the first argument.");
        return EXIT_FAILURE;
    }

    // Without the frontend there is no launcher to start the game, so do it
    // here once the runtime is up. With the frontend, its launcher owns this
    // decision and starting from here would race it.
    // Wait for the renderer's first frame, not a fixed delay.
    //
    // ultramodern's VI thread only seeds a dummy video mode while the game has
    // not started; starting the game before its first tick makes the VI update
    // path dereference a mode that does not exist yet. A sleep here raced that
    // and lost about nine times in ten -- an access violation before librecomp
    // even initialised its heap, with the successful tenth run being the only
    // one that looked like progress.
    std::thread([game_id]() {
        using namespace std::chrono_literals;
        for (int i = 0; i < 1000 && !rayman2::vi_has_ticked().load(std::memory_order_acquire); ++i) {
            std::this_thread::sleep_for(10ms);
        }
        if (!rayman2::vi_has_ticked().load(std::memory_order_acquire)) {
            std::fprintf(stderr, "[rayman2] renderer never presented a frame; starting anyway\n");
        }
        // Load the cached ROM into memory before starting.
        //
        // This is NOT the same thing as validating it. check_all_stored_roms()
        // and is_rom_valid() only establish that a correct dump exists in the
        // config directory; they do not read it. Nothing else does either --
        // start_game() does not, and the port is expected to.
        //
        // Skipping it is not a quiet no-op. librecomp's init() emulates IPL3
        // with a fixed 1 MB DMA from ROM into RDRAM, and do_rom_read() computes
        // its source as rom.data() + physical_addr - rom_base. With an empty
        // span that is an offset from nullptr, and the copy walks into
        // unmapped memory -- an access violation on the game thread, three
        // frames deep in the runtime, with nothing pointing back at the real
        // mistake up here.
        if (!recomp::load_stored_rom(game_id)) {
            message_box("Failed to load the stored ROM from the config directory.");
            return;
        }
        std::fprintf(stderr, "[rayman2] rom loaded: %zu bytes\n",
                     recomp::get_rom().size());

        recomp::start_game(game_id, "");
    }).detach();
#else
    (void)have_rom;
#endif

    // ---- Callbacks ----
    recomp::rsp::callbacks_t rsp_callbacks{};                    // mandatory
    rsp_callbacks.get_rsp_microcode = rayman2_get_rsp_microcode;

    ultramodern::renderer::callbacks_t renderer_callbacks{};     // mandatory
    renderer_callbacks.create_render_context = rayman2::create_render_context;

    ultramodern::gfx_callbacks_t gfx_callbacks{};
    gfx_callbacks.create_gfx    = create_gfx;
    gfx_callbacks.create_window = create_window;
    gfx_callbacks.update_gfx    = update_gfx;

    ultramodern::audio_callbacks_t audio_callbacks{};
    audio_callbacks.queue_samples        = queue_samples;
    audio_callbacks.get_frames_remaining = get_frames_remaining;
    audio_callbacks.set_frequency        = set_frequency;

    ultramodern::input::callbacks_t input_callbacks{};
    input_callbacks.poll_input                = poll_input;
    input_callbacks.get_input                 = get_input;
    input_callbacks.set_rumble                = set_rumble;
    input_callbacks.get_connected_device_info = get_connected_device_info;

    ultramodern::error_handling::callbacks_t error_handling_callbacks{};
    error_handling_callbacks.message_box = message_box;

    ultramodern::threads::callbacks_t threads_callbacks{};
    threads_callbacks.get_game_thread_name = get_game_thread_name;

    recomp::Configuration config{};
    config.argc                     = argc;
    config.argv                     = argv;
    config.project_version          = kProjectVersion;
    config.rsp_callbacks            = rsp_callbacks;
    config.renderer_callbacks       = renderer_callbacks;
    config.audio_callbacks          = audio_callbacks;
    config.input_callbacks          = input_callbacks;
    config.gfx_callbacks            = gfx_callbacks;
    config.error_handling_callbacks = error_handling_callbacks;
    config.threads_callbacks        = threads_callbacks;

#ifdef RAYMAN2_ENABLE_FRONTEND
    // Program identity and menu layout must be registered before recomp::start()
    // brings the renderer up: recompui builds its menus during that bring-up.
    // The id is the directory name the frontend stores settings and saves under,
    // so it is part of the port's on-disk contract and should not drift.
    recompui::programconfig::set_program_id(u8"rayman2-recomp");
    recompui::programconfig::set_program_name("Rayman 2: The Great Escape");

    // Mandatory. recompui throws std::runtime_error during renderer bring-up if
    // no primary font has been registered by the time it builds its menus, and
    // that exception crosses a noexcept boundary -- the process fail-fasts with
    // no output whatsoever, which is a memorably unhelpful way to learn this.
    // The family name is the font's internal one, not its filename.
    recompui::register_primary_font("LatoLatin-Regular.ttf", "LatoLatin");
    recompui::register_extra_font("NotoEmoji-Regular.ttf");
#endif

    // recomp::start() brings up the renderer, and the frontend builds its menus
    // during that bring-up. Anything thrown in there crosses a noexcept
    // boundary on its way out and the process fail-fasts with no message, so
    // the exception is caught and reported here instead of being guessed at.
    rayman2_start_thread_sampler();

    std::fprintf(stderr, "[rayman2] entering recomp::start\n");
    try {
        recomp::start(config);   // blocks until the game exits
    }
    catch (const std::exception& e) {
        std::fprintf(stderr, "[rayman2] FATAL: %s\n", e.what());
        return EXIT_FAILURE;
    }
    catch (...) {
        std::fprintf(stderr, "[rayman2] FATAL: unknown exception\n");
        return EXIT_FAILURE;
    }
    rayman2_stop_thread_sampler();
    std::fprintf(stderr, "[rayman2] recomp::start returned\n");

#ifdef _WIN32
    timeEndPeriod(1);
#endif
    return EXIT_SUCCESS;
}
