// RSP microcode dispatch.
//
// The N64's signal processor runs two kinds of task, and only one of them
// reaches this file.
//
// GRAPHICS tasks never do: RT64 intercepts the display list before the task is
// ever handed to the RSP and renders it on the host GPU. Phase 00 established
// this game uses stock F3DEX.NoN 1.23, which RT64 already has a GBI table entry
// for, so nothing needs recompiling for it.
//
// AUDIO tasks do reach here, and Rayman 2's audio microcode has not been put
// through RSPRecomp yet. Returning a function that reports a normal RSP break
// makes librecomp's run_task() treat the task as completed rather than exiting
// the task thread, so the game keeps running with no sound. Returning nullptr
// instead would print an error and terminate the program, which would make it
// impossible to reach the phase 03 gate over a missing microcode that phase 05
// is scheduled to deal with.
//
// The silence is therefore deliberate and temporary, and it is loud in the log
// the first time it happens so it cannot be mistaken for the audio path working.

#include <cstdint>
#include <cstdio>
#include <cstdlib>
#include <cstring>

#include "librecomp/rsp.hpp"

namespace {
    // Where this game's audio microcode lives. Established by logging the
    // OSTask the game hands to osSpTaskLoad; see recomp/rsp_audio.us.toml
    // for the surrounding layout and how its true length was found.
    constexpr uint32_t kAudioUcodeAddress = 0x80017E60u;

    bool g_warned_unhandled = false;

    // RAYMAN2_NOAUDIOUCODE=1 -- run with the audio microcode switched off.
    //
    // This is an A/B switch for docs/issues/003, not a feature. The audio
    // microcode is the newest thing in the port and the only component that
    // writes to arbitrary RDRAM addresses of its own accord; if the intro's
    // intermittent null call is corruption coming from here, the intro survives
    // with this set and does not without it. Silence is the price of the
    // measurement and the whole of it -- everything else about the run is
    // unchanged, which is what makes the comparison worth anything.
    bool audio_ucode_disabled() {
        static const bool off = []() {
            const char* value = std::getenv("RAYMAN2_NOAUDIOUCODE");
            const bool disabled = value != nullptr && std::strcmp(value, "0") != 0;
            if (disabled) {
                std::fprintf(stderr,
                             "[rayman2] RAYMAN2_NOAUDIOUCODE: the audio microcode will not be run;"
                             " audio tasks are reported complete and the game is silent\n" );
            }
            return disabled;
        }();
        return off;
    }

    // Reports the task as finished without doing anything. See the note above.
    RspExitReason silent_task_stub(uint8_t* /*rdram*/, uint32_t /*ucode_addr*/) {
        return RspExitReason::Broke;
    }
}

// The recompiled audio microcode, generated by scripts/recompile-rsp.sh from
// recomp/rsp_audio.us.toml into RecompiledRsp/rsp_audio.cpp.
RspExitReason rayman2_rsp_audio(uint8_t* rdram, uint32_t ucode_addr);

RspUcodeFunc* rayman2_get_rsp_microcode(const OSTask* task) {
    if (task == nullptr) {
        return silent_task_stub;
    }

    // Dispatch on the microcode address, not the task type.
    //
    // The type says what the game means the task to be; the address says which
    // code it is about to run, and only the second is a safe thing to hand a
    // recompiled function. This game has exactly one non-graphics microcode --
    // logging every distinct one across a run found a single entry -- and it
    // sits at 0x80017E60, immediately after the boot stub the two microcodes
    // share and immediately before F3DEX at 0x80018C80.
    if (task->t.ucode == kAudioUcodeAddress) {
        return audio_ucode_disabled() ? silent_task_stub : rayman2_rsp_audio;
    }

    if (!g_warned_unhandled) {
        g_warned_unhandled = true;
        std::fprintf(stderr,
                     "[rayman2] RSP task type %u microcode 0x%08X is not recompiled; reporting it complete\n",
                     static_cast<unsigned>(task->t.type),
                     static_cast<unsigned>(task->t.ucode));
    }
    return silent_task_stub;
}
